# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.5
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        #MainWindow.resize(757, 600)
        MainWindow.setFixedSize(757, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.userSelection = QtWidgets.QComboBox(self.centralwidget)
        self.userSelection.setGeometry(QtCore.QRect(400, 80, 271, 81))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.userSelection.setFont(font)
        self.userSelection.setObjectName("userSelection")
        self.userSelection.addItem("")
        self.userSelection.addItem("")
        self.userSelection.addItem("")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 100, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 240, 311, 31))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.computeSelection = QtWidgets.QLabel(self.centralwidget)
        self.computeSelection.setGeometry(QtCore.QRect(400, 240, 311, 31))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.computeSelection.setFont(font)
        self.computeSelection.setObjectName("computeSelection")
        self.submitButton = QtWidgets.QPushButton(self.centralwidget)
        self.submitButton.setGeometry(QtCore.QRect(210, 370, 321, 61))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.submitButton.setFont(font)
        self.submitButton.setObjectName("pushButton")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(40, 460, 81, 17))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(40, 490, 91, 17))
        self.label_4.setObjectName("label_4")
        self.userWins = QtWidgets.QLabel(self.centralwidget)
        self.userWins.setGeometry(QtCore.QRect(150, 460, 81, 21))
        self.userWins.setObjectName("userWins")
        self.computerWins = QtWidgets.QLabel(self.centralwidget)
        self.computerWins.setGeometry(QtCore.QRect(150, 490, 91, 17))
        self.computerWins.setObjectName("computerWins")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 757, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionStart_Game = QtWidgets.QAction(MainWindow)
        self.actionStart_Game.setObjectName("actionStart_Game")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")

        self.menuFile.addAction(self.actionQuit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.userSelection.setItemText(0, _translate("MainWindow", "Rock"))
        self.userSelection.setItemText(1, _translate("MainWindow", "Paper"))
        self.userSelection.setItemText(2, _translate("MainWindow", "Scissor"))
        self.label.setText(_translate("MainWindow", "Your Selection"))
        self.label_2.setText(_translate("MainWindow", "Computer Selection"))
        self.computeSelection.setText(_translate("MainWindow", "Computer Selection"))
        self.submitButton.setText(_translate("MainWindow", "Submit"))
        self.label_3.setText(_translate("MainWindow", "User Wins"))
        self.label_4.setText(_translate("MainWindow", "Computer Wins"))
        self.userWins.setText(_translate("MainWindow", "User Wins"))
        self.computerWins.setText(_translate("MainWindow", "Computer Wins"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionStart_Game.setText(_translate("MainWindow", "Start Game"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))

